#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	config_load rfeye
	config_get_bool enabled main enabled 0
	[ "$enabled" = "1" ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/rfeye-agent daemon
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

stop_service() {
	/usr/sbin/rfeye-agent stop >/dev/null 2>&1 || true
}
