#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	config_load rfeye
	config_get_bool enabled main enabled 0
	[ "$enabled" = "1" ] || return 0
	procd_open_instance
	procd_set_param command /usr/bin/rfeye-probe --loop
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
